# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('userProfilenPhone', models.IntegerField()),
                ('userProfileLocal', models.TextField(max_length=1000, verbose_name='\u0110\u1ecba ch\u1ec9')),
                ('userProfileIdentity', models.IntegerField()),
                ('userProfilePermission', models.IntegerField()),
            ],
        ),
    ]
