# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 16:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brandProduct',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=255, unique=True, verbose_name='T\xean h\u1ea3ng s\u1ea3n xu\u1ea5t')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contactID', models.AutoField(primary_key=True, serialize=False)),
                ('contactName', models.CharField(blank=True, max_length=255, verbose_name='H\u1ecd t\xean')),
                ('contactEmail', models.EmailField(max_length=255, verbose_name='Email')),
                ('contactPhone', models.IntegerField(default=0)),
                ('contactContent', models.TextField(blank=True, max_length=1000, verbose_name='N\u1ed9i dung')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventImg', models.ImageField(upload_to='event/%Y/%m/%d', verbose_name='\u1ea3nh \u0111\u1ea1i di\u1ec7n')),
                ('eventDetail', models.TextField(max_length=1000, verbose_name='Chi ti\u1ebft s\u1ef1 ki\u1ec7n')),
                ('eventCreated', models.DateField(default=datetime.date.today)),
                ('eventActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('payID', models.AutoField(primary_key=True, serialize=False)),
                ('payDate', models.DateField(default=datetime.date.today)),
                ('payTotal', models.IntegerField()),
                ('payName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payQuantity', models.IntegerField()),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pay')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productCode', models.CharField(max_length=255, unique=True, verbose_name='M\xe3 s\u1ea3n ph\u1ea9m')),
                ('productName', models.CharField(blank=True, max_length=400, verbose_name='T\xean s\u1ea3n ph\u1ea9m')),
                ('productPrice', models.IntegerField()),
                ('productPricePro', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('productDescription', models.TextField(max_length=1000, verbose_name='Th\xf4ng tin chi ti\u1ebft')),
                ('productPromotion', models.BooleanField(default=False)),
                ('productHot', models.BooleanField(default=False)),
                ('productActive', models.BooleanField(default=False)),
                ('producImg', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='\u1ea2nh s\u1ea3n ph\u1ea9m')),
                ('productCreate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='tyleProduct',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=255, unique=True, verbose_name='T\xean Lo\u1ea1i s\u1ea3n ph\u1ea9m')),
                ('typeBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brandProduct')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productTyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tyleProduct'),
        ),
        migrations.AddField(
            model_name='paydetail',
            name='payProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
