# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181028_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productBrand',
        ),
    ]
