# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_productbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productBrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.brandProduct'),
            preserve_default=False,
        ),
    ]
