# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-03 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_product_productbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productActive',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productHot',
            field=models.BooleanField(default=False, verbose_name='S\u1ea3n ph\u1ea9m hot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPromotion',
            field=models.BooleanField(default=False, verbose_name='Ch\u01b0\u01a1ng tr\xecnh khuy\u1ebfn m\xe3i'),
        ),
    ]
