# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181103_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuNgang',
            fields=[
                ('menuID', models.AutoField(primary_key=True, serialize=False)),
                ('menuTen', models.CharField(max_length=255, unique=True, verbose_name='T\xean Menu')),
            ],
        ),
    ]
