# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20181106_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='LinkName',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='T\xean \u0111\u1ec3 nh\u1edb'),
        ),
    ]
