# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20181106_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slink',
            old_name='Link',
            new_name='LinkURL',
        ),
    ]
