# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20181106_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slink',
        ),
    ]
